/* 每日单词词库 —— 互联网行业 / 日常 / 考研 三类各 50 词
   音标为美式 IPA，p=音标 t=词性 m=释义 e=英文例句 z=例句翻译 */
window.WORDS = {

  tech: [
    { w: "deploy",       p: "/dɪˈplɔɪ/",          t: "v.",     m: "部署；调配",             e: "We deploy the new version every Friday.",        z: "我们每周五部署新版本。" },
    { w: "iterate",      p: "/ˈɪtəreɪt/",         t: "v.",     m: "迭代；反复打磨",          e: "Let's iterate on the design quickly.",           z: "我们快速迭代这个设计吧。" },
    { w: "scalable",     p: "/ˈskeɪləbl/",        t: "adj.",   m: "可扩展的",               e: "The system must be scalable to millions of users.", z: "系统必须能扩展到数百万用户。" },
    { w: "latency",      p: "/ˈleɪtənsi/",        t: "n.",     m: "延迟；时延",             e: "Low latency matters for live video.",            z: "低延迟对直播很重要。" },
    { w: "bandwidth",    p: "/ˈbændwɪdθ/",        t: "n.",     m: "带宽",                   e: "Video eats up a lot of bandwidth.",              z: "视频消耗大量带宽。" },
    { w: "throughput",   p: "/ˈθruːpʊt/",         t: "n.",     m: "吞吐量",                 e: "We doubled the throughput after tuning.",        z: "调优后吞吐量翻倍。" },
    { w: "cache",        p: "/kæʃ/",              t: "n./v.",  m: "缓存；把…存入缓存",       e: "Clear the cache if the page looks wrong.",       z: "页面显示异常就清一下缓存。" },
    { w: "refactor",     p: "/ˌriːˈfæktər/",      t: "v.",     m: "重构（代码）",            e: "We refactored the module to reduce duplication.", z: "我们重构了该模块以减少重复。" },
    { w: "debug",        p: "/ˌdiːˈbʌɡ/",         t: "v.",     m: "调试；排查错误",          e: "I spent all morning debugging this crash.",      z: "我花了一上午调试这个崩溃。" },
    { w: "migrate",      p: "/ˈmaɪɡreɪt/",        t: "v.",     m: "迁移（数据/系统）",        e: "We will migrate the database next month.",       z: "我们下个月迁移数据库。" },
    { w: "protocol",     p: "/ˈproʊtəkɔːl/",      t: "n.",     m: "协议",                   e: "HTTP is an application-layer protocol.",         z: "HTTP 是应用层协议。" },
    { w: "endpoint",     p: "/ˈendpɔɪnt/",        t: "n.",     m: "端点；接口地址",          e: "This endpoint returns a list of orders.",        z: "这个接口返回订单列表。" },
    { w: "payload",      p: "/ˈpeɪloʊd/",         t: "n.",     m: "有效载荷；请求体",        e: "The payload is too large for this API.",         z: "请求体对这个接口来说太大了。" },
    { w: "middleware",   p: "/ˈmɪdlwer/",         t: "n.",     m: "中间件",                 e: "Auth is handled by a middleware.",               z: "鉴权由中间件处理。" },
    { w: "framework",    p: "/ˈfreɪmwɜːrk/",      t: "n.",     m: "框架",                   e: "Which framework does your team use?",            z: "你们团队用哪个框架？" },
    { w: "repository",   p: "/rɪˈpɑːzətɔːri/",    t: "n.",     m: "仓库；代码库",            e: "Push your changes to the repository.",           z: "把你的改动推到代码库。" },
    { w: "commit",       p: "/kəˈmɪt/",           t: "v./n.",  m: "提交（代码）；承诺",       e: "Please commit before you switch branches.",      z: "切分支前请先提交。" },
    { w: "merge",        p: "/mɜːrdʒ/",           t: "v.",     m: "合并",                   e: "I merged the branch into main.",                 z: "我把分支合并到主线了。" },
    { w: "dependency",   p: "/dɪˈpendənsi/",      t: "n.",     m: "依赖；依赖项",            e: "This dependency is no longer maintained.",       z: "这个依赖已经没人维护了。" },
    { w: "container",    p: "/kənˈteɪnər/",       t: "n.",     m: "容器",                   e: "Each service runs in its own container.",        z: "每个服务跑在自己的容器里。" },
    { w: "cluster",      p: "/ˈklʌstər/",         t: "n.",     m: "集群",                   e: "The cluster scaled up automatically.",           z: "集群自动扩容了。" },
    { w: "redundancy",   p: "/rɪˈdʌndənsi/",      t: "n.",     m: "冗余（备份）",            e: "Redundancy keeps the service alive.",            z: "冗余让服务保持可用。" },
    { w: "resilience",   p: "/rɪˈzɪliəns/",       t: "n.",     m: "韧性；容错恢复能力",       e: "We test resilience with chaos engineering.",     z: "我们用混沌工程测试韧性。" },
    { w: "availability", p: "/əˌveɪləˈbɪləti/",   t: "n.",     m: "可用性",                 e: "Our target availability is 99.99%.",             z: "我们的可用性目标是 99.99%。" },
    { w: "concurrency",  p: "/kənˈkɜːrənsi/",     t: "n.",     m: "并发；并发数",            e: "High concurrency broke the old design.",         z: "高并发击垮了旧设计。" },
    { w: "asynchronous", p: "/eɪˈsɪŋkrənəs/",     t: "adj.",   m: "异步的",                 e: "Use asynchronous calls to avoid blocking.",      z: "用异步调用避免阻塞。" },
    { w: "authentication", p: "/ɔːˌθentɪˈkeɪʃn/", t: "n.",     m: "身份认证",               e: "Two-factor authentication is required.",         z: "必须开启双因素认证。" },
    { w: "authorization", p: "/ˌɔːθərəˈzeɪʃn/",   t: "n.",     m: "授权",                   e: "Check authorization before returning data.",     z: "返回数据前先校验授权。" },
    { w: "encryption",   p: "/ɪnˈkrɪpʃn/",        t: "n.",     m: "加密",                   e: "Encryption protects data in transit.",           z: "加密保护传输中的数据。" },
    { w: "session",      p: "/ˈseʃn/",            t: "n.",     m: "会话；场次",              e: "The session expires in thirty minutes.",         z: "会话三十分钟后过期。" },
    { w: "query",        p: "/ˈkwɪri/",           t: "n./v.",  m: "查询；询问",              e: "This query is slow without an index.",           z: "这个查询没有索引会很慢。" },
    { w: "schema",       p: "/ˈskiːmə/",          t: "n.",     m: "模式；表结构",            e: "We changed the schema and broke the client.",    z: "我们改了表结构，把客户端搞挂了。" },
    { w: "transaction",  p: "/trænˈzækʃn/",       t: "n.",     m: "事务；交易",              e: "Wrap both writes in one transaction.",           z: "把两次写入放在同一个事务里。" },
    { w: "sharding",     p: "/ˈʃɑːrdɪŋ/",         t: "n.",     m: "分片（数据库拆分）",       e: "Sharding solved our write bottleneck.",          z: "分片解决了写入瓶颈。" },
    { w: "throttle",     p: "/ˈθrɑːtl/",          t: "v./n.",  m: "限流；节流",              e: "We throttle clients that send too many requests.", z: "我们对请求过多的客户端限流。" },
    { w: "monitoring",   p: "/ˈmɑːnɪtərɪŋ/",      t: "n.",     m: "监控",                   e: "Monitoring caught the issue in seconds.",        z: "监控几秒钟内就发现了问题。" },
    { w: "observability", p: "/əbˌzɜːrvəˈbɪləti/", t: "n.",    m: "可观测性",               e: "Observability is more than dashboards.",         z: "可观测性不只是几张看板。" },
    { w: "dashboard",    p: "/ˈdæʃbɔːrd/",        t: "n.",     m: "仪表盘；数据看板",        e: "The dashboard shows traffic by region.",         z: "看板按地区展示流量。" },
    { w: "metric",       p: "/ˈmetrɪk/",          t: "n.",     m: "指标；度量",              e: "Which metric defines success here?",             z: "这里用哪个指标衡量成功？" },
    { w: "retention",    p: "/rɪˈtenʃn/",         t: "n.",     m: "留存（率）；保留",        e: "Retention improved after the redesign.",         z: "改版后留存率提升了。" },
    { w: "conversion",   p: "/kənˈvɜːrʒn/",       t: "n.",     m: "转化（率）",              e: "A faster page lifted conversion by 12%.",        z: "页面变快让转化率提升了 12%。" },
    { w: "engagement",   p: "/ɪnˈɡeɪdʒmənt/",     t: "n.",     m: "参与度；互动量",          e: "Short videos drive engagement.",                 z: "短视频能带动互动量。" },
    { w: "monetization", p: "/ˌmʌnɪtəˈzeɪʃn/",    t: "n.",     m: "变现；商业化",            e: "Monetization comes after retention.",            z: "先做留存，再谈变现。" },
    { w: "churn",        p: "/tʃɜːrn/",           t: "n./v.",  m: "用户流失；搅动",          e: "Price hikes caused higher churn.",               z: "涨价导致流失率上升。" },
    { w: "roadmap",      p: "/ˈroʊdmæp/",         t: "n.",     m: "路线图；规划",            e: "The roadmap changed after the review.",          z: "评审后路线图调整了。" },
    { w: "milestone",    p: "/ˈmaɪlstoʊn/",       t: "n.",     m: "里程碑",                 e: "We hit the first milestone early.",              z: "我们提前达成了第一个里程碑。" },
    { w: "sprint",       p: "/sprɪnt/",           t: "n.",     m: "冲刺（迭代周期）",         e: "This sprint we focus on stability.",             z: "这个迭代我们专注稳定性。" },
    { w: "backlog",      p: "/ˈbæklɔːɡ/",         t: "n.",     m: "待办积压；需求池",         e: "Let's groom the backlog on Monday.",             z: "周一我们梳理一下需求池。" },
    { w: "stakeholder",  p: "/ˈsteɪkhoʊldər/",    t: "n.",     m: "利益相关方",              e: "Keep stakeholders informed weekly.",             z: "每周同步进展给相关方。" },
    { w: "prototype",    p: "/ˈproʊtətaɪp/",      t: "n.",     m: "原型",                   e: "We built a prototype in two days.",              z: "我们两天做出了原型。" }
  ],

  daily: [
    { w: "grocery",      p: "/ˈɡroʊsəri/",        t: "n.",     m: "食品杂货",               e: "I need to buy groceries after work.",            z: "下班后我得去买点菜。" },
    { w: "laundry",      p: "/ˈlɔːndri/",         t: "n.",     m: "待洗衣物；洗衣",          e: "The laundry is still in the machine.",           z: "衣服还在洗衣机里。" },
    { w: "commute",      p: "/kəˈmjuːt/",         t: "v./n.",  m: "通勤",                   e: "My commute takes forty minutes.",                z: "我通勤要四十分钟。" },
    { w: "errand",       p: "/ˈerənd/",           t: "n.",     m: "差事；跑腿的事",          e: "I have a few errands to run downtown.",          z: "我要去市区办几件杂事。" },
    { w: "appointment",  p: "/əˈpɔɪntmənt/",      t: "n.",     m: "预约；约定",              e: "I have a dentist appointment at three.",         z: "我三点约了牙医。" },
    { w: "receipt",      p: "/rɪˈsiːt/",          t: "n.",     m: "收据；发票",              e: "Keep the receipt in case you return it.",        z: "留着收据，万一要退货。" },
    { w: "refund",       p: "/ˈriːfʌnd/",         t: "n./v.",  m: "退款；退还",              e: "They gave me a full refund.",                    z: "他们给我全额退款了。" },
    { w: "warranty",     p: "/ˈwɔːrənti/",        t: "n.",     m: "保修；质保",              e: "The laptop is still under warranty.",            z: "这台笔记本还在保修期内。" },
    { w: "landlord",     p: "/ˈlændlɔːrd/",       t: "n.",     m: "房东",                   e: "The landlord raised the rent again.",            z: "房东又涨房租了。" },
    { w: "tenant",       p: "/ˈtenənt/",          t: "n.",     m: "租客；房客",              e: "The tenant pays rent on the first day.",         z: "租客每月一号交租。" },
    { w: "utility",      p: "/juːˈtɪləti/",       t: "n.",     m: "公用事业；水电费",        e: "Utilities are included in the rent.",            z: "水电费包含在房租里。" },
    { w: "subscription", p: "/səbˈskrɪpʃn/",      t: "n.",     m: "订阅（服务）",            e: "I cancelled three subscriptions this month.",    z: "这个月我退订了三个服务。" },
    { w: "deposit",      p: "/dɪˈpɑːzɪt/",        t: "n./v.",  m: "押金；定金；存放",        e: "We paid a deposit of two months' rent.",         z: "我们付了两个月房租的押金。" },
    { w: "budget",       p: "/ˈbʌdʒɪt/",          t: "n./v.",  m: "预算",                   e: "We are on a tight budget this month.",           z: "这个月我们预算很紧。" },
    { w: "savings",      p: "/ˈseɪvɪŋz/",         t: "n.",     m: "储蓄；存款",              e: "He dipped into his savings for the trip.",       z: "他动用了存款去旅行。" },
    { w: "leftover",     p: "/ˈleftoʊvər/",       t: "n./adj.", m: "剩饭；剩余的",           e: "We had leftovers for lunch.",                    z: "我们午饭吃的是剩菜。" },
    { w: "takeaway",     p: "/ˈteɪkəweɪ/",        t: "n.",     m: "外卖；要点",              e: "Let's just order takeaway tonight.",             z: "今晚就点外卖吧。" },
    { w: "recipe",       p: "/ˈresəpi/",          t: "n.",     m: "食谱；配方",              e: "She shared her family recipe with me.",          z: "她把她家的食谱分享给我了。" },
    { w: "ingredient",   p: "/ɪnˈɡriːdiənt/",     t: "n.",     m: "原料；成分",              e: "Read the ingredients before you buy it.",        z: "买之前先看配料表。" },
    { w: "seasoning",    p: "/ˈsiːzənɪŋ/",        t: "n.",     m: "调味料",                 e: "Add seasoning at the very end.",                 z: "调味料最后再放。" },
    { w: "simmer",       p: "/ˈsɪmər/",           t: "v.",     m: "用文火慢炖",              e: "Let it simmer for twenty minutes.",              z: "小火炖二十分钟。" },
    { w: "appliance",    p: "/əˈplaɪəns/",        t: "n.",     m: "家用电器",               e: "The kitchen appliances are brand new.",          z: "厨房电器都是全新的。" },
    { w: "vacuum",       p: "/ˈvækjuːm/",         t: "v./n.",  m: "用吸尘器打扫；真空",       e: "I vacuum the floor every Sunday.",               z: "我每周日吸一次地。" },
    { w: "clutter",      p: "/ˈklʌtər/",          t: "n./v.",  m: "杂乱；使凌乱",            e: "Clear the clutter off your desk.",               z: "把桌上的杂物清一清。" },
    { w: "tidy",         p: "/ˈtaɪdi/",           t: "adj./v.", m: "整洁的；收拾",           e: "Please tidy up before guests arrive.",           z: "客人来之前请收拾一下。" },
    { w: "wardrobe",     p: "/ˈwɔːrdroʊb/",       t: "n.",     m: "衣柜；全部衣物",          e: "She rebuilt her whole wardrobe.",                z: "她把整个衣柜的衣服都换了。" },
    { w: "sunscreen",    p: "/ˈsʌnskriːn/",       t: "n.",     m: "防晒霜",                 e: "Wear sunscreen even on cloudy days.",            z: "阴天也要涂防晒。" },
    { w: "moisturizer",  p: "/ˈmɔɪstʃəraɪzər/",   t: "n.",     m: "保湿霜",                 e: "Apply moisturizer after washing your face.",     z: "洗完脸后涂保湿霜。" },
    { w: "pharmacy",     p: "/ˈfɑːrməsi/",        t: "n.",     m: "药房",                   e: "The pharmacy closes at ten.",                    z: "药房十点关门。" },
    { w: "prescription", p: "/prɪˈskrɪpʃn/",      t: "n.",     m: "处方；药方",              e: "This medicine needs a prescription.",            z: "这个药需要处方。" },
    { w: "symptom",      p: "/ˈsɪmptəm/",         t: "n.",     m: "症状",                   e: "A cough is a common symptom.",                   z: "咳嗽是常见症状。" },
    { w: "allergy",      p: "/ˈælərdʒi/",         t: "n.",     m: "过敏",                   e: "He has a serious peanut allergy.",               z: "他对花生严重过敏。" },
    { w: "clinic",       p: "/ˈklɪnɪk/",          t: "n.",     m: "诊所",                   e: "There is a clinic around the corner.",           z: "拐角处有个诊所。" },
    { w: "vaccination",  p: "/ˌvæksɪˈneɪʃn/",     t: "n.",     m: "接种疫苗",               e: "Vaccination is free for children.",              z: "儿童接种疫苗是免费的。" },
    { w: "insurance",    p: "/ɪnˈʃʊrəns/",        t: "n.",     m: "保险",                   e: "Travel insurance saved us a lot.",               z: "旅行保险帮我们省了不少钱。" },
    { w: "parking",      p: "/ˈpɑːrkɪŋ/",         t: "n.",     m: "停车；停车位",            e: "Parking is impossible downtown.",                z: "市中心根本找不到车位。" },
    { w: "traffic",      p: "/ˈtræfɪk/",          t: "n.",     m: "交通；流量",              e: "I was stuck in traffic for an hour.",            z: "我堵在路上一个小时。" },
    { w: "detour",       p: "/ˈdiːtʊr/",          t: "n./v.",  m: "绕行路线",               e: "We had to take a detour around the bridge.",     z: "我们只能绕桥走。" },
    { w: "itinerary",    p: "/aɪˈtɪnəreri/",      t: "n.",     m: "行程单；旅行计划",        e: "Send me the itinerary before we fly.",           z: "出发前把行程单发我。" },
    { w: "luggage",      p: "/ˈlʌɡɪdʒ/",          t: "n.",     m: "行李",                   e: "My luggage did not arrive with the plane.",      z: "我的行李没跟着航班到。" },
    { w: "boarding",     p: "/ˈbɔːrdɪŋ/",         t: "n.",     m: "登机；上车",              e: "Boarding starts in ten minutes.",                z: "十分钟后开始登机。" },
    { w: "layover",      p: "/ˈleɪoʊvər/",        t: "n.",     m: "中转停留",               e: "We have a three-hour layover in Tokyo.",         z: "我们在东京中转停留三小时。" },
    { w: "reservation",  p: "/ˌrezərˈveɪʃn/",     t: "n.",     m: "预订",                   e: "I made a reservation for two at seven.",         z: "我订了七点两个人的位子。" },
    { w: "souvenir",     p: "/ˌsuːvəˈnɪr/",       t: "n.",     m: "纪念品",                 e: "She bought souvenirs for the whole team.",       z: "她给整个团队都买了纪念品。" },
    { w: "neighbor",     p: "/ˈneɪbər/",          t: "n.",     m: "邻居",                   e: "Our neighbors are very quiet.",                  z: "我们邻居很安静。" },
    { w: "balcony",      p: "/ˈbælkəni/",         t: "n.",     m: "阳台",                   e: "We had coffee on the balcony.",                  z: "我们在阳台上喝了咖啡。" },
    { w: "elevator",     p: "/ˈelɪveɪtər/",       t: "n.",     m: "电梯",                   e: "The elevator is out of service again.",          z: "电梯又坏了。" },
    { w: "faucet",       p: "/ˈfɔːsɪt/",          t: "n.",     m: "水龙头",                 e: "The faucet is dripping all night.",              z: "水龙头整晚都在滴水。" },
    { w: "plumber",      p: "/ˈplʌmər/",          t: "n.",     m: "水管工",                 e: "We need to call a plumber.",                     z: "我们得叫个水管工。" },
    { w: "recycle",      p: "/ˌriːˈsaɪkl/",       t: "v.",     m: "回收利用",               e: "We recycle paper and glass at home.",            z: "我们在家回收纸张和玻璃。" }
  ],

  kaoyan: [
    { w: "abandon",      p: "/əˈbændən/",         t: "v.",     m: "放弃；抛弃",              e: "He abandoned the plan without explanation.",     z: "他毫无解释地放弃了这个计划。" },
    { w: "abolish",      p: "/əˈbɑːlɪʃ/",         t: "v.",     m: "废除；取消",              e: "The law was abolished last year.",               z: "该法律去年被废除了。" },
    { w: "absorb",       p: "/əbˈzɔːrb/",         t: "v.",     m: "吸收；使专注",            e: "Plants absorb carbon dioxide.",                  z: "植物吸收二氧化碳。" },
    { w: "abstract",     p: "/ˈæbstrækt/",        t: "adj./n.", m: "抽象的；摘要",           e: "The theory is too abstract to apply.",           z: "这个理论太抽象，无法应用。" },
    { w: "abundant",     p: "/əˈbʌndənt/",        t: "adj.",   m: "丰富的；大量的",          e: "The region has abundant natural resources.",     z: "该地区自然资源丰富。" },
    { w: "accelerate",   p: "/əkˈseləreɪt/",      t: "v.",     m: "加速；促进",              e: "Technology accelerates social change.",          z: "技术加速社会变革。" },
    { w: "accommodate",  p: "/əˈkɑːmədeɪt/",      t: "v.",     m: "容纳；适应；提供住处",     e: "The hall can accommodate 500 people.",           z: "大厅可容纳五百人。" },
    { w: "accumulate",   p: "/əˈkjuːmjəleɪt/",    t: "v.",     m: "积累；堆积",              e: "Dust accumulates quickly here.",                 z: "这里灰尘积得很快。" },
    { w: "acknowledge",  p: "/əkˈnɑːlɪdʒ/",       t: "v.",     m: "承认；致谢；确认收到",     e: "She acknowledged her mistake at once.",          z: "她立刻承认了错误。" },
    { w: "acquire",      p: "/əˈkwaɪər/",         t: "v.",     m: "获得；学到",              e: "Children acquire language naturally.",           z: "儿童自然习得语言。" },
    { w: "adapt",        p: "/əˈdæpt/",           t: "v.",     m: "适应；改编",              e: "Species must adapt to survive.",                 z: "物种必须适应才能生存。" },
    { w: "adequate",     p: "/ˈædɪkwət/",         t: "adj.",   m: "足够的；适当的",          e: "The evidence is not adequate.",                  z: "证据并不充分。" },
    { w: "adjacent",     p: "/əˈdʒeɪsnt/",        t: "adj.",   m: "邻近的；毗连的",          e: "Our offices are adjacent to the park.",          z: "我们办公室紧邻公园。" },
    { w: "administer",   p: "/ədˈmɪnɪstər/",      t: "v.",     m: "管理；执行；施用",        e: "The fund is administered by a committee.",       z: "该基金由一个委员会管理。" },
    { w: "advocate",     p: "/ˈædvəkeɪt/",        t: "v./n.",  m: "提倡；拥护者",            e: "She advocates reform of the system.",            z: "她主张改革这一制度。" },
    { w: "aesthetic",    p: "/esˈθetɪk/",         t: "adj.",   m: "美学的；审美的",          e: "The building has great aesthetic value.",        z: "这栋建筑有很高的审美价值。" },
    { w: "aggravate",    p: "/ˈæɡrəveɪt/",        t: "v.",     m: "加剧；使恶化",            e: "Stress aggravates the illness.",                 z: "压力会加重病情。" },
    { w: "alleviate",    p: "/əˈliːvieɪt/",       t: "v.",     m: "减轻；缓解",              e: "The medicine alleviated his pain.",              z: "药物减轻了他的疼痛。" },
    { w: "allocate",     p: "/ˈæləkeɪt/",         t: "v.",     m: "分配；拨给",              e: "We allocated more funds to research.",           z: "我们把更多资金分配给研究。" },
    { w: "ambiguous",    p: "/æmˈbɪɡjuəs/",       t: "adj.",   m: "模糊的；有歧义的",        e: "His answer was deliberately ambiguous.",         z: "他的回答故意含糊其辞。" },
    { w: "amend",        p: "/əˈmend/",           t: "v.",     m: "修改；修订",              e: "The contract was amended twice.",                z: "这份合同修改了两次。" },
    { w: "analogy",      p: "/əˈnælədʒi/",        t: "n.",     m: "类比；类推",              e: "He drew an analogy between the brain and a computer.", z: "他把大脑与计算机做了类比。" },
    { w: "anonymous",    p: "/əˈnɑːnɪməs/",       t: "adj.",   m: "匿名的",                 e: "The donation came from an anonymous source.",    z: "这笔捐款来自匿名人士。" },
    { w: "anticipate",   p: "/ænˈtɪsɪpeɪt/",      t: "v.",     m: "预料；期望",              e: "We anticipate strong demand.",                   z: "我们预计需求旺盛。" },
    { w: "apparatus",    p: "/ˌæpəˈrætəs/",       t: "n.",     m: "器械；装置；机构",         e: "The lab bought new apparatus.",                  z: "实验室买了新仪器。" },
    { w: "arbitrary",    p: "/ˈɑːrbɪtreri/",      t: "adj.",   m: "任意的；专断的",          e: "The choice seemed completely arbitrary.",        z: "这个选择显得完全随意。" },
    { w: "articulate",   p: "/ɑːrˈtɪkjuleɪt/",    t: "v./adj.", m: "清晰表达；表达清楚的",    e: "She articulated the problem clearly.",           z: "她把问题讲得很清楚。" },
    { w: "assert",       p: "/əˈsɜːrt/",          t: "v.",     m: "断言；主张；维护",         e: "He asserted that the data was wrong.",           z: "他断言数据有误。" },
    { w: "assess",       p: "/əˈses/",            t: "v.",     m: "评估；估价",              e: "We need to assess the risks first.",             z: "我们需要先评估风险。" },
    { w: "assimilate",   p: "/əˈsɪməleɪt/",       t: "v.",     m: "同化；吸收（知识）",       e: "It takes time to assimilate new ideas.",         z: "吸收新观念需要时间。" },
    { w: "attribute",    p: "/əˈtrɪbjuːt/",       t: "v./n.",  m: "归因于；属性",            e: "She attributes her success to hard work.",       z: "她把成功归因于努力。" },
    { w: "authentic",    p: "/ɔːˈθentɪk/",        t: "adj.",   m: "真实的；可信的",          e: "This is an authentic ancient vase.",             z: "这是一件真正的古董花瓶。" },
    { w: "autonomy",     p: "/ɔːˈtɑːnəmi/",       t: "n.",     m: "自治；自主权",            e: "Teachers want more autonomy in class.",          z: "教师希望课堂上有更多自主权。" },
    { w: "bias",         p: "/ˈbaɪəs/",           t: "n./v.",  m: "偏见；使有偏见",          e: "The study suffers from selection bias.",         z: "该研究存在选择偏差。" },
    { w: "boost",        p: "/buːst/",            t: "v./n.",  m: "促进；提高",              e: "The policy boosted consumer confidence.",        z: "该政策提振了消费者信心。" },
    { w: "breach",       p: "/briːtʃ/",           t: "n./v.",  m: "违反；缺口；攻破",        e: "The company breached the contract.",             z: "该公司违反了合同。" },
    { w: "capacity",     p: "/kəˈpæsəti/",        t: "n.",     m: "容量；能力；产能",         e: "The plant is running at full capacity.",         z: "工厂正满负荷运转。" },
    { w: "cater",        p: "/ˈkeɪtər/",          t: "v.",     m: "迎合；提供饮食",          e: "The show caters to young audiences.",            z: "这个节目迎合年轻观众。" },
    { w: "cease",        p: "/siːs/",             t: "v.",     m: "停止；终止",              e: "The rain finally ceased at dawn.",               z: "雨在黎明时终于停了。" },
    { w: "coherent",     p: "/koʊˈhɪrənt/",       t: "adj.",   m: "连贯的；条理清楚的",       e: "He gave a coherent account of events.",          z: "他对事件做了连贯的叙述。" },
    { w: "coincide",     p: "/ˌkoʊɪnˈsaɪd/",      t: "v.",     m: "同时发生；相一致",         e: "My holiday coincides with the festival.",        z: "我的假期正好赶上那个节日。" },
    { w: "compel",       p: "/kəmˈpel/",          t: "v.",     m: "强迫；迫使",              e: "Nothing can compel him to apologize.",           z: "没什么能逼他道歉。" },
    { w: "compensate",   p: "/ˈkɑːmpenseɪt/",     t: "v.",     m: "补偿；弥补",              e: "The firm compensated the workers.",              z: "公司赔偿了工人。" },
    { w: "competent",    p: "/ˈkɑːmpɪtənt/",      t: "adj.",   m: "有能力的；称职的",         e: "She is a competent manager.",                    z: "她是一位称职的管理者。" },
    { w: "comprehensive", p: "/ˌkɑːmprɪˈhensɪv/", t: "adj.",   m: "全面的；综合的",          e: "We need a comprehensive review.",                z: "我们需要一次全面审查。" },
    { w: "compromise",   p: "/ˈkɑːmprəmaɪz/",     t: "n./v.",  m: "妥协；折中；损害",         e: "Both sides reached a compromise.",               z: "双方达成了妥协。" },
    { w: "conceive",     p: "/kənˈsiːv/",         t: "v.",     m: "构想；设想；怀孕",         e: "It is hard to conceive of such a scale.",        z: "很难想象这样的规模。" },
    { w: "condemn",      p: "/kənˈdem/",          t: "v.",     m: "谴责；宣判",              e: "Leaders condemned the attack.",                  z: "各国领导人谴责了这次袭击。" },
    { w: "confront",     p: "/kənˈfrʌnt/",        t: "v.",     m: "面对；对抗",              e: "We must confront the real problem.",             z: "我们必须直面真正的问题。" },
    { w: "consensus",    p: "/kənˈsensəs/",       t: "n.",     m: "共识；一致意见",          e: "The team reached a consensus quickly.",          z: "团队很快达成了共识。" }
  ]

};
